export const firstYearGroupsNames: string[] = [
  "ARCHITETTURA DEGLI ELABORATORI E LABORATORIO",
  "ELEMENTI DI ANALISI MATEMATICA 1",
  "FONDAMENTI DI INFORMATICA",
  "MATEMATICA DISCRETA",
  "PROGRAMMAZIONE I E LABORATORIO",
  "PROGRAMMAZIONE II",
  "ULTERIORI CONOSCENZE LINGUISTICHE",
];

export const secondYearGroupsNames: string[] = [
  "ALGORITMI E LABORATORIO",
  "BASI DI DATI",
  "ELEMENTI DI ANALISI MATEMATICA 2",
  "INGEGNERIA DEL SOFTWARE",
  "RETI DI CALCOLATORI",
  "SISTEMI OPERATIVI",
  "[Discussione] I&M 2019_2020",
];

export const thirdYearGroupsNames: string[] = [
  "CALCOLO NUMERICO",
  "COMPUTER GRAFICA",
  "DIGITAL FORENSICS",
  "FISICA",
  "INFORMATICA MUSICALE",
  "INTERNET SECURITY",
  "INTRODUZIONE AL DATA MINING",
  "IT LAW",
  "LABORATORIO DI SISTEMI A MICROCONTROLLORE",
  "METODI MATEMATICI E STATISTICI",
  "PROGRAMMAZIONE MOBILE",
  "PROGRAMMAZIONE PARALLELA SU ARCHITETTURE GPU",
  "SISTEMI CENTRALI",
  "SOCIAL MEDIA MANAGEMENT",
  "STARTUP DI IMPRESA E MODELLI DI BUSINESS",
  "SVILUPPO DI GIOCHI DIGITALI",
  "TECHNOLOGIES FOR ADVANCED PROGRAMMING",
  "TECNOLOGIE PER I SISTEMI DISTRIBUITI E IL WEB CON LABORATORIO",
  "Web Development 2020",
];
