name: Build & Deploy

on:
  push:
    branches: [msin]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name $name
          git config --global user.email $email
          git remote set-url origin https://${token}@github.com/${repository}
          npm run deploy
        env:
          name: 'github-actions[bot]'
          email: 'github-actions[bot]@users.noreply.github.com'
          token: ${{ secrets.GHPAGES_TOKEN }}
          repository: ${{ github.repository }}
